version: "3.8"

services:
  # The Media Empire
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ./data/plex/config:/config
      - /mnt/media/movies:/movies # Change this path to match the 4.1TB drive mount
      - /mnt/media/tv:/tv
    restart: unless-stopped
