import os
import time
import json
import urllib.request

WATCH_DIR = "/vault/dna"
OUTPUT_FILE = "/vault/DNA_Profile.md"
OLLAMA_URL = "http://host.docker.internal:11434/api/generate"

# Dictionary of high-impact SNPs we care about
CRITICAL_SNPS = {
    "rs429358": "APOE (Alzheimer's / Lipids)",
    "rs7412": "APOE (Alzheimer's / Lipids)",
    "rs1801133": "MTHFR (Methylation / B9)",
    "rs1801131": "MTHFR (Methylation / B9)",
    "rs1333049": "9p21 (Cardiovascular)",
    "rs7903146": "TCF7L2 (Type 2 Diabetes)"
}

def parse_dna_file(filepath):
    print(f"Parsing DNA file: {filepath}")
    found_snps = {}
    
    with open(filepath, 'r') as f:
        for line in f:
            if line.startswith('#'):
                continue
            parts = line.strip().split()
            # Standard 23andMe format: rsid, chromosome, position, genotype
            if len(parts) >= 4:
                rsid = parts[0]
                genotype = parts[3]
                if rsid in CRITICAL_SNPS:
                    found_snps[rsid] = {
                        "name": CRITICAL_SNPS[rsid],
                        "genotype": genotype
                    }
                    print(f"Found match: {CRITICAL_SNPS[rsid]} ({rsid}) -> Genotype: {genotype}")
                    
    return found_snps

def analyze_with_llm(snp_data):
    print("Sending anomalies to LLM for clinical analysis...")
    
    prompt = f"""
    Act as a precision medicine genomic engineer. 
    The user has submitted their raw DNA file. A programmatic scan detected the following critical high-impact SNPs:
    
    {json.dumps(snp_data, indent=2)}
    
    Please provide:
    1. A brief summary of what these specific genotypes mean for their biological hardware.
    2. Specific, actionable lifestyle and dietary overrides (e.g. if APOE4, avoid saturated fat).
    3. Specific supplement protocol overrides (e.g. if MTHFR, use methylfolate instead of folic acid).
    
    Do NOT give generic advice. Give advice ONLY tailored to these specific genetic markers.
    Format your output cleanly in Markdown, using bullet points and headers.
    """
    
    data = {
        "model": "llama3",
        "prompt": prompt,
        "stream": False
    }
    
    req = urllib.request.Request(OLLAMA_URL, json.dumps(data).encode("utf-8"), headers={'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode())
            return result.get('response', '')
    except Exception as e:
        print(f"Error calling Ollama: {e}")
        return "Error generating analysis. Make sure Ollama is running on the host machine."

def main():
    if not os.path.exists(WATCH_DIR):
        os.makedirs(WATCH_DIR)
        
    print(f"🧬 DNA Parser Online. Watching {WATCH_DIR} for raw .txt files...")
    processed_files = set()
    
    while True:
        try:
            for filename in os.listdir(WATCH_DIR):
                if filename.endswith(".txt") and filename not in processed_files:
                    filepath = os.path.join(WATCH_DIR, filename)
                    
                    # 1. Parse DNA
                    snp_data = parse_dna_file(filepath)
                    
                    if snp_data:
                        # 2. Analyze with LLM
                        analysis = analyze_with_llm(snp_data)
                        
                        # 3. Write to Vault
                        with open(OUTPUT_FILE, 'w') as f:
                            f.write("# 🧬 Genomic Profile\n\n")
                            f.write("> Automatically generated by Sovereign Atom DNA Parser\n\n")
                            f.write(analysis)
                            
                        print(f"✅ Successfully wrote genetic profile to {OUTPUT_FILE}")
                    else:
                        print(f"⚠️ No critical SNPs found in {filename}.")
                        
                    processed_files.add(filename)
            
            time.sleep(10)
        except Exception as e:
            print(f"Error in main loop: {e}")
            time.sleep(10)

if __name__ == "__main__":
    main()
